name: CI

on:
  pull_request:
    branches: [main]

env:
  POSTGRES_USER: documentstudies
  POSTGRES_PASSWORD: documentstudies
  POSTGRES_DB: documentstudies_test
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: documentstudies
          POSTGRES_PASSWORD: documentstudies
          POSTGRES_DB: documentstudies_test
          POSTGRES_HOST: localhost
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.1"
          bundler-cache: true
      - name: Install JS Dependencies
        run: npm install
      - name: Run Rails tests
        run: RAILS_ENV=test ./bin/rails test
      - name: Run JS tests
        run: npm test
